-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 12:28:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blockexplorer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blockexplorer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blockexplorer` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blockexplorer` ;

-- -----------------------------------------------------
-- Table `blockexplorer`.`blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blockexplorer`.`blocks` (
  `height` INT(11) NOT NULL,
  `hash` VARCHAR(64) NOT NULL,
  `prevHash` VARCHAR(64) NOT NULL,
  `merkle` VARCHAR(64) NOT NULL,
  `timestamp` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`height`),
  UNIQUE INDEX `height_UNIQUE` (`height` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blockexplorer`.`txs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blockexplorer`.`txs` (
  `txID` INT(11) NOT NULL AUTO_INCREMENT,
  `hash` VARCHAR(64) NOT NULL,
  `height` INT(11) NOT NULL,
  PRIMARY KEY (`txID`),
  UNIQUE INDEX `txID_UNIQUE` (`txID` ASC),
  INDEX `height_idx` (`height` ASC),
  CONSTRAINT `height`
    FOREIGN KEY (`height`)
    REFERENCES `blockexplorer`.`blocks` (`height`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blockexplorer`.`outputs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blockexplorer`.`outputs` (
  `outID` INT(11) NOT NULL AUTO_INCREMENT,
  `txID` INT(11) NOT NULL,
  `index` INT(11) NOT NULL,
  `amount` BIGINT(20) NULL DEFAULT NULL,
  `address` VARCHAR(59) NOT NULL,
  `used` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`outID`),
  UNIQUE INDEX `outID_UNIQUE` (`outID` ASC),
  INDEX `txID_idx` (`txID` ASC),
  CONSTRAINT `txID`
    FOREIGN KEY (`txID`)
    REFERENCES `blockexplorer`.`txs` (`txID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blockexplorer`.`inputs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blockexplorer`.`inputs` (
  `inID` INT(11) NOT NULL AUTO_INCREMENT,
  `outID` INT(11) NOT NULL,
  `txID` INT(11) NOT NULL,
  PRIMARY KEY (`inID`),
  UNIQUE INDEX `inID_UNIQUE` (`inID` ASC),
  INDEX `outID_idx` (`outID` ASC),
  CONSTRAINT `outID`
    FOREIGN KEY (`outID`)
    REFERENCES `blockexplorer`.`outputs` (`outID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
